from django.core.mail import send_mail
from django.conf import settings

def send_deep_wish():
    send_mail(
        "Hello, dude this is my BOT.", 
        """
        Hell dude, as i told you that i will send you the message at
        Exactly 12:00 AM so if you wanna know what did i use ask me 
        tommorow when we're gonna go on shopping.
        ::
        ::
        Well, Now the word. "Happy Birthday Dude!!"
        ::
        Hope you'll get everything you wanted and this is your best 
        birthday althought the best is about to come.
        ::
        So, I am probably asleep right now if you are awake at the time
        of arival of this message. So now you should sleep.
        ::
        Waiting for shopping... {*~*}/
        ::
        Generated By - DeepWish [A Django App to send wishes.]
        ::
        Developed By - Divcorn.
        """,
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=['vivekascoder@gmail.com',]
    )